# DDP
gpus: "2,3"
flag: train

# Log
log_dir: "./log/mesorch_df_train_2"

# Task
if_predict_label: false
if_predict_mask: true

# Model
model:
  name: Mesorch
  init_config:
    conv_pretrain: true
    seg_pretrain_path: /home/59435a/Forensic_hub/weight/mit_b3.pth

# Train dataset
train_dataset:
    name: DocDataset
    dataset_name: Bigdataset
    init_config:
      path: /home/59435a/Forensic_hub/data/big_dataset
      suffix_img: 
        - ".png"
        - ".jpeg"
        - ".jpg"

test_dataset:
# FCD
  - name: DocDataset
    dataset_name: fcd
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/FCD
  - name: DocDataset
    dataset_name: fcd_recompress
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/FCD_recompress
# FUNSD
  - name: DocDataset
    dataset_name: funsd
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/Funsd
      suffix_img: ".png"
  - name: DocDataset
    dataset_name: funsd_recompress
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/funsd_recompress
      suffix_img: ".png"
# Maif authentic
  - name: DocDataset
    dataset_name: Maif_authentic
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/Maif_authentic
  - name: DocDataset
    dataset_name: Maif_authentic_recompress
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/Maif_authentic_recompress
# Maif forged
  - name: DocDataset
    dataset_name: Maif_Forged
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/Maif_Forged
# SCD
  - name: DocDataset
    dataset_name: scd
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/SCD
  - name: DocDataset
    dataset_name: scd_recompress
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/SCD_recompress
# sroie
  - name: DocDataset
    dataset_name: sroie
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/Sroie
  - name: DocDataset
    dataset_name: sroie_recompress
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/Sroie_recompress
# Testingset
  - name: DocDataset
    dataset_name: DocTamperData_test
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/TestingSet
  - name: DocDataset
    dataset_name: DocTamperData_test_recompress
    init_config:
      path: /home/59435a/Forensic_hub/data/big_test/TestingSet_recompress



#   name: DocDataset
#   dataset_name: DocTamperData_train
#   init_config:
#     path: /home/59435a/Forensic_hub/data/Doctamper/TrainingSet
#   # name: DocDataset
#   # dataset_name: DocTamperData_fcd
#   # init_config:
#     # path: /home/59435a/Forensic_hub/data/Doctamper/FCD
# test_dataset:
#   - name: DocDataset
#     dataset_name: DocTamperData_test
#     init_config:
#       path: /home/59435a/Forensic_hub/data/Doctamper/TestingSet
#   - name: DocDataset
#     dataset_name: DocTamperData_scd
#     init_config:
#       path: /home/59435a/Forensic_hub/data/Doctamper/SCD
#   - name: DocDataset
#     dataset_name: DocTamperData_fcd
#     init_config:
#       path: /home/59435a/Forensic_hub/data/Doctamper/FCD

# Transform
transform:
  name: DocTransform
  init_config:
    norm_type: image_net

# Evaluators
evaluator:
  # - name: ImageF1
  #   init_config:
  #     threshold: 0.5
  - name: PixelIOU
    init_config:
      threshold: 0.5
  - name: PixelF1
    init_config:
      threshold: 0.5

# Training related
batch_size: 10
test_batch_size: 14
epochs: 20
accum_iter: 1
record_epoch: 0  # Save the best only after record epoch.

# Test related
no_model_eval: false
test_period: 1

# Logging & TensorBoard
log_per_epoch_count: 10

# DDP & AMP settings
find_unused_parameters: true
use_amp: false

# Optimizer parameters
weight_decay: 0.05
lr: 0.0001
blr: 0.001
min_lr: 0.00001
warmup_epochs: 1

# Device and training control
device: "cuda"
seed: 42
resume: ""
start_epoch: 0
num_workers: 8
pin_mem: true

# Distributed training parameters
# world_size: 1
# local_rank: -1
dist_on_itp: false
dist_url: "env://"

