name: MLOps Pipeline
on: 
  pull_request:
    paths-ignore:
      - 'dvc.lock'
  workflow_dispatch:
jobs:
  mlops:
    name: MLOps
    uses: socles-ia/mlops/.github/workflows/mlops.yml@master
    secrets: inherit